deploy:
	gcloud functions deploy jma-xml-warning-possibility-update \
		--project=weatherbox-217409 \
		--region=asia-northeast1 \
		--trigger-topic=jma-xml-warning-possibility-update \
		--runtime=nodejs10 \
		--entry-point=handler
